### ISSUE TITLE
Firefox 에서 이미지 드래그앤드롭 문제

### ISSUE THREAD

**Issue by imyaman** [RedgooseDev/react-photo-layout-editor#10]
https://redgoosedev.github.io/react-photo-layout-editor/ 에 Firefox 로 방문하여, 오른쪽 이미지를 왼쪽 그리드에 드래그앤드롭 되지 않습니다.

Firefox 55.0, Windows 10 64bit 쓰고 있습니다.

**Comment by redgoose-dev** [comment]
이크.. 브라우저 테스트를 계속 미뤄왔더니.. ㅠㅠ
확인했습니다~

**Comment by imyaman** [comment]
쓰면서 고치는거죠. ^^ 테스트에 인력이 많이 필요하실 텐데... 관심 갖고 보겠습니다.

**Comment by redgoose-dev** [comment]
fb22bc7 수정완료했습니다. :)
