### ISSUE TITLE
Learn how to attach text.

### ISSUE THREAD

**Issue by redgoose-dev** [RedgooseDev/react-photo-layout-editor#12]
> This post was write by google translator.

In the `react-photo-layout-editor`, the" Text editor "function is out of range.

----

There are two ways.

1. Add a toolbar button similar to "Setting" function from the forked Repository.
1. Separate the text addition function and layout creation function.

### Plan A

![new mockup 1](https://user-images.githubusercontent.com/1978100/40460549-432802f2-5f42-11e8-8970-be4a2bea3076.png)

It's a difficult way.

Fork out `react-photo-layout-editor` and add text functionality.
You need to add your own features.

----

![new mockup 2](https://user-images.githubusercontent.com/1978100/40460550-4350c7dc-5f42-11e8-86b2-0596a2d177be.png)

You can add features without modifying `react-photo-layout-editor`.  
Press `Next step` button to go to` Add text `function.  
You can create `Add text` function.

`react-photo-layout-editor` can be extracted in Canvas format.  
https://github.com/RedgooseDev/react-photo-layout-editor/wiki/API.Util#export

**Comment by redgoose-dev** [comment]
@olee2002 please read post.

**Comment by olee2002** [comment]
Thank you for looking into the options!
