### ISSUE TITLE
안녕하세요. 이미지 만들려고 할때 CORS 에러가 나는데 해결방법 아시나요?

### ISSUE THREAD

**Issue by allysung** [RedgooseDev/react-photo-layout-editor#13]
'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access.

aws s3에 있는 이미지 가져와서 make 이미지 할려 해당 CORS 메시지가 나오는데 해결방법 혹시 알수 있을까요?ㅎㅎ
그럼 감사합니다!! 수고하세요!

**Comment by redgoose-dev** [comment]
@sungkyunLee 어떻게 했을때 나온 상황인지 알려주세요. 한두번 경험해본적이 있었는데 도메인이 다른 이미지와 canvas의 문제가 있는거 같더라구요. ;;;

https://html.com/attributes/img-crossorigin/#CORS_and_the_crossorigin_attribute 관련 이슈라고 보입니다.

**Comment by redgoose-dev** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTML/CORS_enabled_image
이 부분과 관련이 되어있는데 회사 동료가 s3에서 cors에 관한 설정을 할 수 있다고 하네요..

제가 s3를 사용하지 않아서 정확한 답변을 알 수 없지만..
https://docs.aws.amazon.com/ko_kr/AmazonS3/latest/dev/cors.html
참고 해보시구요...

여기가 좀더 구체적인 답변인거 같아 보이네요.
https://stackoverflow.com/questions/17533888/s3-access-control-allow-origin-header

결론적으로 이미지 헤더가 `Access-Control-Allow-Origin: *` 상태로 받아올 수 있다면 편집된 이미지를 만들 수 있을겁니다.

**Comment by allysung** [comment]
헛!! 안녕하세요!! 답변 감사합니다!!ㅎ react dev server 로 작업중이였고 s3 에 public 으로 접근 가능한 url 리스트를 가져와서 이미지를 다시 만들려고(makeImage) 하니깐 Access to Image at 'https://s3.ap-northeast-2.amazonaws.com/truecoupon-dev/img/product/201806/32%28new%29-product-url-2839348103.jpg' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access. 이렇게 발생했어요!! ㅎㅎ

올려주신 답변 참고해서 해결해 보도록 하겠습니다. 정말 감사합니다.!!

**Comment by redgoose-dev** [comment]
제가 질문을 제대로 읽지 않아서 댓글 적고나서 질문의 의도를 알았네요.
저도 겪어봤던 현상이었고, 서버에서 해줘야하는 일도 있고, 클라이언트쪽은 최대한 대처는 해두었습니다. :)

성공하시길 바랄께요~

**Comment by allysung** [comment]
와우!! 감사합니다!! 성공했어요!! 알려주신 방법대로 하니깐 잘 되네요!!ㅎㅎ
친철한 답변 감사합니다!! ㅎ

**Comment by redgoose-dev** [comment]
성공과 하나 알아감에 대하여 축하드려요 👍 
이게 많은 도움이 되길 바래요~

이 이슈는 닫을께요~

**Comment by kihyun0103** [comment]
ㅑㅏ
