### ISSUE TITLE
Just can't preview pics.

### ISSUE THREAD

**Issue by TingAlex** [RedgooseDev/react-photo-layout-editor#15]
I have installed react-photo-layout-editor, and copied some code from dev folder. After configuring some loaders in webpack and other stuff, now everything works fine except the preview part of pictures. 
 
![layout_problem](https://user-images.githubusercontent.com/16840938/59076368-3e54cf80-8908-11e9-983d-b3e3456665ac.gif)

As you can see, pics will be added successfully after I click it. But it just won't show up in the preview part. Could you help me? Thanks a loooot!

**Comment by TingAlex** [comment]
If I want to use react-router, and when I navigate to this page, I won't preview successfully, but if I use it  directly, I mean only render this component, then everything will be fine. That's interesting... How could I workaround it?

**Comment by TingAlex** [comment]
Well, after serial hours, I finally found that the AntDesign cause this problem. Once I remove it, everything will work correctly.... Now I will try to solve this conflict.

**Comment by redgoose-dev** [comment]
@TingAlex 

This is usually a problem with the image path. Check out the preview elements using "Chrome DevTools".
External elements can affect the preview area.

ps. Please understand that we use Google translation.

**Comment by TingAlex** [comment]
Thank you very much for your reply!
This morning I finally worked it out by compare CSS line by line.
And the problem is that AntDesign use -webkit-appearence:button style on the [type-"button"]!!!
I use !important to reset this style on the .ple-side .ple-sideItems span. And now everything works fine! 
![problem-occurs](https://user-images.githubusercontent.com/16840938/59139632-ea5cf000-89c6-11e9-806d-57d5536b7d38.png)

![solved problem!!](https://user-images.githubusercontent.com/16840938/59139713-80911600-89c7-11e9-86c8-5e2900d2419c.png)

Thanks again!
