### ISSUE TITLE
upgrade project

### ISSUE THREAD

**Issue by redgoose-dev** [RedgooseDev/react-photo-layout-editor#18]
슬슬 좀 다시 다듬어야할때가 온것같다.

아마 전체적으로 손보면서 상태관리 라이브러리를 `redux` -> `recoil`로 변경시키면서 좀 공부해보고싶은데 이정도 되면 아마 재작업하면서 컴포넌트들을 전부 포팅해봐야하지 않을까 느껴진다.

이걸 작업하면서 요즘 `react`를 어떻게 작업해야하는지 감좀 잡을 수 있을거라는 기대감도 들고, 요즘 부쩍 이 프로젝트를 다듬어보고 싶어진다.

일단 할일목록에 추가하기 위하여 이슈로 남겨둔다.

**Comment by redgoose-dev** [comment]
이건 무기한으로 중단..
시도해보면서 리코일의 한계를 맛보기도 하고 현재 사용하는 방식에서 맞지않는 부분도 맛보기도 했다.

**Comment by pbtaffi** [comment]
Hello @redgoose-dev,

this project looks very interesting and meets several requirements of my current project. Do you have any plans to update or upgrade it ?  Please let me know. Thank you.

**Comment by redgoose-dev** [comment]
@fashionado Sorry for the translator.

Thank you for your interest.
We have stopped the upgrade, but if we do it again, we will reopen this issue or create a new one.
If a new version is made, it will start with `2.0`.
